services:
  devcontainer:
    image: "swift:6.3.2-noble@sha256:c4336909a71b2e69b884f4078cdf98c0cd081911632cb349ef72abc4cbed69fc"
    working_dir: ${WORKSPACE_DIR}
    env_file:
      - .env
    environment:
      PATH: /root/.swiftpm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ${GIT_REPO}:${GIT_REPO}:rw
      - ${WORKSPACE_DIR}:${WORKSPACE_DIR}:rw
    command: sleep infinity
