name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Swift 6.3.3
        uses: SwiftyLab/setup-swift@v1.14.0
        with:
          swift-version: "6.3.3"

      - name: Install linters (SwiftLint & SwiftFormat)
        run: |
          brew update
          brew install swiftlint swiftformat

      - name: SwiftLint
        run: swiftlint --config .swiftlint.yml

      - name: SwiftFormat (lint mode)
        run: swiftformat --lint . --config .swiftformat

  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift-version: ["6.2", "6.3.3"]
    runs-on: ${{ matrix.os }}
    needs: lint

    steps:
      - uses: actions/checkout@v7

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1.14.0
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build --configuration debug

      - name: Test
        run: swift test --parallel
